// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhpvqtveflxoduazasml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocHZxdHZlZmx4b2R1YXphc21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNjEyMzQsImV4cCI6MjA4OTkzNzIzNH0.EfULQEV-jdaEqn89Qi1IEbz50uHPVZqyLD7YW4G11ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});